name: Deploy to S3

on:
  push:
    branches:
      - feature/notity  # main 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'  # Node.js 18.16.0 버전 설정

      - name: Install dependencies
        run: npm install

      - name: Start development server
        run: npm run dev &
        continue-on-error: false  # dev 실행 실패 시 워크플로우 중단
        env:
          NODE_ENV: development  # 필요 시 환경 변수 설정

      - name: Check if server is running
        run: |
          sleep 10  # 서버가 시작될 때까지 잠시 대기
          curl -I http://localhost:5173  # 서버 상태 확인 (포트 번호는 dev 설정에 맞게 변경)
        if: success()

      - name: Configure AWS credentials
        if: success()  # dev 서버가 성공적으로 실행되었을 때만 실행
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy to S3
        if: success()  # 서버가 성공적으로 실행되었을 때만 실행
        run: npm run deploy
